version: '3'
services:
  backend:
    container_name: backend-service
    build:
      context: ./backend
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend
    ports:
      - "8090:80"